CREATE TABLE Todo(
  Id INT PRIMARY KEY NOT NULL,
  Hash CHAR(40) NOT NULL,
  Author TEXT NOT NULL,
  Date TEXT NOT NULL,
  FileName TEXT NOT NULL,
  LineNumber INT NOT NULL,
  Line TEXT NOT NULL,
  Priority INT NOT NULL DEFAULT 0
)
